name: ts
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - holoviews
  - pytest
  - python=3.11.4
  - scipy
  - ipykernel
  - scikit-image
  - numba
  - selenium
  - python-chromedriver-binary
  - ipympl
